platform :ios, '9.0'

target 'onboarding' do
pod 'XLForm', '~> 3.2'
pod 'JVFloatLabeledTextField', '~> 1.1'
pod 'XLData', '~> 2.0'
pod 'SHSPhoneComponent', '~> 2.15'
pod 'Firebase'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'SignatureView', '~> 1.1'
pod 'ResearchKit', '~> 1.3'
pod 'MXSegmentedPager', '~> 3.0'

use_frameworks!
pod 'XLPagerTabStrip', '~> 5.0'

end
